### ISSUE TITLE
Swift Package

### ISSUE THREAD

**Issue by marcussc** [ehn-digital-green-development/base45-swift#4]
Hey hey,

I was just wondering what is needed to get https://github.com/ehn-digital-green-development/base45-swift/tree/distribution/swiftpackage merged? 

Is there something I can help out with to get it done?

Thanks!

**Comment by dirkx** [comment]
Yes - I made a pull request - #7 - if you could check that It works for you too - lets merge it.

**Comment by dirkx** [comment]
Closes with pr #7 and tag 1.00
