### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by stmitt** [ehn-digital-green-development/base45-swift#9]
The current versioning is not a valid [semantic version](https://semver.org). The swift package manager only allows specifying versions which use the semantic versioning scheme and therefore the current latest release "1.01" is not usable. 

Would it be possible to create a new release e.g. "1.0.1" which would allow us to specify the version in our package?

**Comment by UBaggeler** [comment]
https://github.com/ehn-dcc-development/base45-swift/releases/tag/1.0.1 created
